import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "/css/fontStyle.css";
import "/css/Uiverse.css";
import Navbar from "./components/Navbar";
import { Providers } from "./providers";

const fontStyle = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Next Practice",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning={true}>
      <body className={fontStyle.className}>
        <Providers>
          <div className="">
            <Navbar />

            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
